### ISSUE TITLE
ADR 2; Maakt het resultaat van de WG Routering onderdeel uit van de GF Adressering?

### ISSUE THREAD

**Issue by RonObbens** [minvws/generiekefuncties-adressering#141]
Bij het totstandkomen van de Notified Pull voor de BGZ is een subwerkgroep aan de slag gegaan met een stuk routering op basis van activity definitions. Dat heeft geleidt tot een resultaat waarvan bepaald moet worden of dat resultaat opgenomen kan worden in de GF Adressering.

**Comment by bramwesselo** [comment]
Nee, het resultaat van TA/WG Routering maakt geen onderdeel uit van GF Adressering, maar TA Routering is afhankelijk van GF Adressering. Van belang is dat in HealthCareService.type verwezen kan worden naar (externe) ActivityDefinitions om specificeren welke workflows of services ondersteund worden door de HealthCareService. 

Edit van @stevenvegt:
`ActivityDefinitions` worden dus zelf geen onderdeel van de GF-Adressering en zijn dus ook niet doorzoekbaar binnen de GF.

**Comment by bramwesselo** [comment]
Vraag aan GF Adressering: wordt het zoeken op HealthCareService.type ondersteund vanuit GF Adressering? 
M.a.w.: wordt searchparameter  'service-type' op HealthCareService ondersteund zoals in [CapabilityStatement van mCSD](https://profiles.ihe.net/ITI/mCSD/CapabilityStatement-IHE.mCSD.CareServicesSelectiveSupplier.json.html) wordt gespecificeerd?

**Comment by RizAhmed85** [comment]
Drie scenario's:
1) Ik weet welke zorgaanbieder ik zoek (patiënt is daar in zorg of ik weet dat deze aanbieder betrokken is/wordt bij de zorg) en wil weten welke adresseerbare punten deze heeft;
2) Ik weet welke soort zorgaanbieder ik zoek en wil de GF adressering gebruiken om een zorgaanbieder te vinden met adresseerbare punten;
3) Ik weet welke soort zorg ik zoek en wil de GF adressering gebruiken om een zorgaanbieder te vinden met adresseerbare punten die plek heeft voor deze specifieke patiënt.

Vraag is wat de scope is van GF adressering en om daar een besluit voor te formuleren.

**Comment by stevenvegt** [comment]
De scope van de GF-Adressering is m.i. als volgt:

1. Het vinden van entiteiten:
   * Uniek op basis van een unieke identifier (UZI, KVK, URA, AGB etc, zie #136 )
   * Nul of meerdere, op basis van niet unieke eigenschappen (naam, service-type, regio etc)
2. Het vinden van andere entiteiten op basis van relaties tussen entiteiten (via relationele queries), zoals: 
   * Welke Organisatie hoort bij deze afdeling
   * Welke Vestigingen van deze organisatie bevinden zich in regio-Noord?
   * Wat is het Adresseerbare-punt van deze Organisatie van type "verwijzen-fhir"
   * Welke Vestigingen van deze organisatie levert zorg van HealthcareService van type 'service-type'?
3. Het raadplegen van informatie op een entiteit:
   * Wat is het telefoonnummer van deze Vestiging
   * Wat is het technisch adres van Endpoint?

In de functie staan dus semi-statische informatie. Dus geen informatie die dynamisch is (zoals vrije bedden en capaciteit). Hiervoor moet je een losse use-case inrichten en afspreken. Technische adressen van services die hierin ondersteunen kunnen dan als EndPoint worden gepubliceerd.

**Comment by stevenvegt** [comment]
Voorstel:

Vraag: Maakt de TA Routering onderdeel uit van de GF Adressering?
Beslissing: Nee, de TA routering is geen onderdeel van de GF adressering. De TA Routering kan gebruik maken van de generieke functie adressering voor het lokaliseren van organisaties en endpoints, maar er kan niet worden gezocht op ActivityDefinitions.

Procesvoorstel:

Werkgroep GF adressering werkt de generieke functie verder uit en presenteert dit aan de WG TA routering. Die werkt dan zelf uit hoe de GF adressering toegepast kan worden vanuit de TA.
