### ISSUE TITLE
ADR 3; We richten in de ordening tbv adressering een base-url / adres-url in per zorg-entiteit met een verwijzing naar een adresboek

### ISSUE THREAD

**Issue by RonObbens** [minvws/generiekefuncties-adressering#150]

**Comment by RizAhmed85** [comment]
![Image](https://github.com/minvws/generiekefuncties-adressering/assets/147600963/5721ff2e-139d-4311-a90f-63aa5436679d)



![Image](https://github.com/minvws/generiekefuncties-adressering/assets/147600963/87303caa-2117-4d93-ba92-9df0dc818388)

**Comment by stevenvegt** [comment]
We zetten deze verkenning door in #155
