### ISSUE TITLE
ADR 4; achter het base-url/adres-url komt er een zorg-adresboek met daarin alle adresseerbare punten van die zorg-identiteit

### ISSUE THREAD

**Issue by RonObbens** [minvws/generiekefuncties-adressering#151]
# Achtergrond
* Adresseerbare punten
* Endpoints
* Healthcare Services
* 
# Relevante ADRs
* #155

**Comment by RizAhmed85** [comment]
![Image](https://github.com/minvws/generiekefuncties-adressering/assets/147600963/5721ff2e-139d-4311-a90f-63aa5436679d)



![Image](https://github.com/minvws/generiekefuncties-adressering/assets/147600963/87303caa-2117-4d93-ba92-9df0dc818388)

**Comment by stevenvegt** [comment]
Dit gaat denk ik over de base-url van de `Organization`?
Het voorstel (en titel) is dus eigenlijk:
_Een (zorg)organisatie implementeerd de rol **Care Services Update Supplier**_

**Comment by stevenvegt** [comment]
We zetten deze verkenning door in #155
