### ISSUE TITLE
Een endpoint moet kunnen verwijzen naar een uitwisselsysteem

### ISSUE THREAD

**Issue by stevenvegt** [minvws/generiekefuncties-adressering#35]
### Gebruiker

Anders

### Wat wil de gebruiker doen?

Een endpoint moet kunnen verwijzen naar een uitwisselsysteem

### Motivatie

Endpoint horen bij een EUS, en moeten dus ook die relatie kunnen krijgen.

### Extra informatie

Deze requirement kwam uit de werkgroep van 27 februari

**Comment by ltieleman** [comment]
Voorstel om deze draft te sluiten, dit kan worden opgelost met #31.
Wellicht dit als voorbeeld/motivatie van metadata opnemen bij #31
