### ISSUE TITLE
Als zorgorganisatie/zorgverlener/leverancier wil ik dat er onderscheid gemaakt wordt tussen aantoonbare meerwaarde voor eindgebruikers van de generieke functie adressering.

### ISSUE THREAD

**Issue by ltieleman** [minvws/generiekefuncties-adressering#50]
### Gebruiker

Behandelaar

### Wat wil de gebruiker doen?

Als zorgorganisatie/zorgverlener/leverancier wil ik dat er onderscheid gemaakt wordt tussen aantoonbare meerwaarde voor eindgebruikers van de generieke functie adressering:
- t.o.v. de bestaande situatie begin 2024 - nulmeting
- op korte termijn – fase 1 – eind 2025 (in samenhang met specifieke & generieke normen)
- op lange termijn – fase 2 – nader te bepalen, op basis van opgedane ervaring in fase 1

### Motivatie

- Meerwaarde in algemene zin: Om alle inspanningen voor de generieke functie adressering te kunnen rechtvaardigen.
- Onderscheid meerwaarde korte/lange termijn: Om een bepaalde fasering aan te brengen, zodat er ook op korte termijn al meerwaarde geleverd kan worden.

**Comment by stevenvegt** [comment]
Voorstel voor een nieuwe tekst:

Als gebruiker wil ik dat de diverse ontwikkelplateuas van de adresseringsfunctie voor mij aantoonbare meerwaarde gaan opleveren
