### ISSUE TITLE
Als gebruiker is het mogelijk om geregistreerde werknemers van een organisatie of suborganisatie op te vragen

### ISSUE THREAD

**Issue by NellyAnbeek** [minvws/generiekefuncties-adressering#65]
### Gebruiker

Persoon

### Wat wil de gebruiker doen?

Als gebruiker is het mogelijk om geregistreerde werknemers van een organisatie of suborganisatie op te vragen

### Motivatie

x

### Extra informatie

x

**Comment by VWSLANS** [comment]
Samenvoegen met #64
