### ISSUE TITLE
Als leverancier van een elektronisch uitwisselsysteem kan ik een rol hebben bij het helpen verzamelen en gebruiken van adresgegevens.

### ISSUE THREAD

**Issue by BertineUithoven** [minvws/generiekefuncties-adressering#85]
a.	Het is een samenwerking tussen zorgaanbieders en leveranciers.
b.	Validatie van gegevens waar mogelijk.
c.	Delen van gegevens met toestemming van de bronhouder.
d.	Vraag of dit een requirement is voor de generieke functie of een procesrequirement.

**Comment by BertineUithoven** [comment]
Wat wordt er bedoeld met 'elektronisch uitwisselsysteem' en 'adresgegevens'?

**Comment by VWSLANS** [comment]
Afgewezen geen requirement

**Comment by GTukker** [comment]
dubbel met #31 en #42?
