### ISSUE TITLE
Als zorgaanbieder wil ik middels een autorisatie mechanisme gegevens al dan niet beschikbaar stellen (conform NEN7518).

### ISSUE THREAD

**Issue by PascalvanderHall** [minvws/generiekefuncties-adressering#92]
Als zorgaanbieder wil ik middels een autorisatie mechanisme gegevens al dan niet beschikbaar stellen (conform NEN7518).

**Comment by VWSLANS** [comment]
Dat gaat deze norm niet regelen. Is een organisatievraagstuk.

**Comment by Settelsm** [comment]
Welke vorm van autorisatie is dan wel noodzakelijk?
